apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: external-secrets-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    vault:
      server: https://vault-infra.safaricomet.net
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: ${datacenter}-${tenant}
          role: ${datacenter}-${tenant}-role
          serviceAccountRef:
            name: vault-integration-sa
            namespace: kube-system
