apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-addons-flux
  namespace: flux-system
spec:
  interval: 1m
  url: oci://harbor-harbor-core.harbor.svc.cluster.local:80/platform/tanzu-addons-flux
  insecure: true
  ref:
    tag: latest
  secretRef:
    name: harbor-registry-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: addons-bootstrap
  namespace: flux-system
spec:
  interval: 5m
  path: ./
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: k8s-addons-flux
  postBuild:
    substituteFrom:
    - kind: Secret
      name: substitute-config
      optional: false