apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: local-harbor-helm-repo
  namespace: flux-system
spec:
  interval: 30m0s
  type: oci
  url: oci://harbor-harbor-core.harbor.svc.cluster.local/platform
  insecure: true
  # certSecretRef:
  #   name: safaricomet.net-tls
