{
 "title": "Avi-Controller",
 "tags": [ "avi" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values({type=\"serviceengine\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Virtualservices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avi_controller_stats_avg_num_active_vs{instance=\"$instance\", type=\"controller\"})"
    }
   ]
  },
  {
   "title": "Number of Backend Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avi_controller_stats_avg_num_backend_servers{instance=\"$instance\", type=\"controller\"})"
    }
   ]
  },
  {
   "title": "Number of Service Engines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) ({instance=\"$instance\",type=\"serviceengine\"}))"
    }
   ]
  },
  {
   "title": "Controller CPU%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avi_controller_stats_avg_cpu_usage{instance=\"$instance\", type=\"controller\"}",
     "legendFormat": "{{uuid}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.controller.*.controller_stats_avg_cpu_usage, 6)"
    }
   ]
  },
  {
   "title": "Controller Mem%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avi_controller_stats_avg_mem_usage{instance=~\"$instance\", type=\"controller\"}",
     "legendFormat": "{{uuid}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.controller.*.controller_stats_avg_mem_usage, 6)"
    }
   ]
  },
  {
   "title": "Average Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avi_controller_stats_avg_disk_usage{instance=\"$instance\", type=\"controller\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avi_controller_stats_avg_disk_write_bytes{instance=\"$instance\", type=\"controller\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avi_controller_stats_avg_disk_read_bytes{instance=\"$instance\", type=\"controller\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}