{
 "title": "Avi-Pool Specific",
 "tags": [ "avi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values({type=\"pool\"},instance)"
    }
   },
   {
    "name": "tenant",
    "query": {
     "query": "label_values({type=\"pool\", instance=~\"$instance\"},tenant)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values({type=\"pool\", instance=~\"$instance\", tenant=\"$tenant\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avi_l4_server_avg_bandwidth{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"})",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "CPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avi_l4_server_avg_new_established_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"})",
     "target": "network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_new_established_conns"
    }
   ]
  },
  {
   "title": "Concurrent Conns",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avi_l4_server_avg_complete_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"})",
     "target": "network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_complete_conns"
    }
   ]
  },
  {
   "title": "Healthscore",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avi_healthscore_health_score_value{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"})",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.healthscore)"
    }
   ]
  },
  {
   "title": "Server Side Timing",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(avi_l4_server_avg_total_rtt{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"})",
     "legendFormat": "Server RTT",
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_server_avg_total_rtt, 'Server RTT')"
    },
    {
     "expr": "avg(avi_l7_server_avg_application_response_time{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"})",
     "legendFormat": "App Response",
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_server_avg_application_response_time, 'App Rsponse')"
    }
   ]
  },
  {
   "title": "Pool Server Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avi_l4_server_avg_bandwidth{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"}",
     "legendFormat": "{{server}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "Connections Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avi_l4_server_avg_new_established_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"}",
     "legendFormat": "{{server}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_new_established_conns, 6)"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avi_l4_server_avg_complete_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"}",
     "legendFormat": "{{server}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_complete_conns, 6)"
    }
   ]
  },
  {
   "title": "Avg Server Side  Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avi_l7_server_avg_resp_latency{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"}",
     "legendFormat": "{{server}}",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_server_avg_resp_latency)"
    }
   ]
  },
  {
   "title": "Avg Server Application Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avi_l7_server_avg_application_response_time{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"}",
     "legendFormat": "{{server}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.pool_members_up, 8, 9)"
    }
   ]
  },
  {
   "title": "RX Packets Per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avi_l4_server_avg_rx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"}",
     "legendFormat": "{{server}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_rx_pkts, 6)"
    }
   ]
  },
  {
   "title": "TX Packets Per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avi_l4_server_avg_tx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"}",
     "legendFormat": "{{server}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_tx_pkts, 6)"
    }
   ]
  },
  {
   "title": "Server Healthscore",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avi_healthscore_health_score_value{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"}",
     "legendFormat": "{{server}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.healthscore, 6)"
    }
   ]
  },
  {
   "title": "Average Client Lossy Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "avi_l4_server_avg_lossy_connections{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"}",
     "legendFormat": "{{server}}",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_lossy_connections)"
    }
   ]
  },
  {
   "title": "Pool Member - Open Conns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "avi_l4_server_avg_open_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"}",
     "legendFormat": "{{server}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_open_conns, 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total TX packets from",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum_over_time(avi_l4_server_avg_tx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"} [$__range]) * 60",
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_tx_pkts, 60), 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total RX packets from",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 44 },
   "targets": [
    {
     "expr": "sum_over_time(avi_l4_server_avg_rx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"} [$__range]) * 60",
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_rx_pkts, 60), 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total TX Bytes to",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum_over_time(avi_l4_server_avg_tx_bytes{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"} [$__range]) * 60",
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_tx_bytes, 60), 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total RX Bytes from",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "targets": [
    {
     "expr": "sum_over_time(avi_l4_server_avg_rx_bytes{instance=~\"$instance\", tenant=~\"$tenant\",type=\"pool\",name=\"$pool\"} [$__range]) * 60",
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_rx_bytes, 60), 8, 9)"
    }
   ]
  }
 ]
}