{
 "title": "Avi-Service Engines Total",
 "tags": [ "avi" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values({type=\"serviceengine\"},instance)"
    }
   },
   {
    "name": "tenant",
    "query": {
     "query": "label_values({type=\"serviceengine\", instance=~\"$instance\"},tenant)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total SE Average Bandwidth (5min avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(avi_se_if_avg_bandwidth{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\"})",
     "legendFormat": "total bandwidth",
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_bandwidth), 'totalbandwidth')"
    }
   ]
  },
  {
   "title": "Top 5 SE - Average Bandwidth (5min avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(5, avi_se_if_avg_bandwidth{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_bandwidth, 5), 6)"
    }
   ]
  },
  {
   "title": "Top 5 - SE CPU%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5,avi_se_stats_avg_cpu_usage{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_cpu_usage, 5), 6)"
    }
   ]
  },
  {
   "title": "Lowest 5 - SE Healthscores",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bottomk(5,avi_healthscore_health_score_value{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(lowestAverage(sortByMinima(network-script.avi.$location.$environment.$device.serviceengine.*.healthscore), 5), 6)"
    }
   ]
  },
  {
   "title": "Number of Service Engines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (name) ({instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\"}))",
     "legendFormat": "serviceengine",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.count, 5)"
    }
   ]
  },
  {
   "title": "SE RX PPS  - Top 10",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,avi_se_if_avg_rx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_rx_pkts, 10), 6)"
    }
   ]
  },
  {
   "title": "Connection Memory Usage - Top 10",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,avi_se_stats_avg_connection_mem_usage{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_connection_mem_usage, 10), 6)"
    }
   ]
  },
  {
   "title": "SE CPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,avi_se_stats_avg_connections{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_connections, 10), 6)"
    }
   ]
  }
 ]
}