{
 "title": "IIS Dashbored",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "VM/Host Name",
    "query": {
     "query": "label_values(iis_uptime_seconds,host_name)"
    }
   },
   {
    "name": "iisSite",
    "label": "IIS Site",
    "query": {
     "query": "label_values(iis_connection_active,iis_site)"
    }
   },
   {
    "name": "app_pool",
    "label": "App_Pool",
    "query": {
     "query": "label_values(iis_application_pool_uptime{host_name=\"$hostname\", iis_application_pool!=\".NET.*\"},iis_application_pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IIS Application Pool State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iis_application_pool_state{host_name=\"$hostname\", iis_application_pool=\"$app_pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IIS Application Pool UpTime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iis_application_pool_uptime{host_name=\"$hostname\", iis_application_pool=\"$app_pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IIS Connection Attempt Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(iis_connection_attempt_count_total{host_name=~\"$hostname\", iis_site=\"$iisSite\"}[$__rate_interval])",
     "legendFormat": "{{iis_site}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(iis_uptime_seconds{host_name=\"$hostname\", iis_site=\"$iisSite\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IIS Active Connection",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iis_connection_active{host_name=~\"$hostname\", iis_site=\"$iisSite\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IIS Request Count ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(request) (rate(iis_request_count_total{host_name=\"$hostname\", iis_site=\"$iisSite\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IIS Anonymous Connection ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(iis_connection_anonymous_total{host_name=\"$hostname\", iis_site=\"$iisSite\"}[$__rate_interval])",
     "legendFormat": "{{iis_site}}"
    }
   ]
  },
  {
   "title": "IIS Thread Active",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iis_thread_active{host_name=\"$hostname\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "IIS Request Queue Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(iis_application_pool) (iis_request_queue_age_max_milliseconds{host_name=\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IIS Request Rejected Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(iis_application_pool) (rate(iis_request_rejected_total{host_name=~\"$hostname\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IIS Request Queue Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum by(__name__) (iis_request_queue_count{host_name=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IIS Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(iis_network_io_bytes_total{host_name=~\"$hostname\", iis_site=\"$iisSite\"}[$__rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "IIS Network File Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "iis_network_file_count_total{host_name=~\"$hostname\", iis_site=\"$iisSite\"}",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "IIS Network Blocked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(iis_network_blocked_bytes_total{host_name=~\"$hostname\", iis_site=\"$iisSite\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}