{
 "title": "MySQL Status",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "vm_group",
    "label": "VM Group",
    "query": {
     "query": "label_values(mysql_uptime_seconds_total{mysql_instance_endpoint=\"localhost:3306\"},vm_group)"
    }
   },
   {
    "name": "node_name",
    "label": "VM/Host Name",
    "query": {
     "query": "label_values(mysql_uptime_seconds_total{vm_group=\"$vm_group\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_uptime_seconds_total{host_name=\"$node_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_connection_count_total{host_name=\"$node_name\"}",
     "legendFormat": "mysql_connection_count_total"
    },
    {
     "expr": "mysql_max_used_connections{host_name=\"$node_name\"}",
     "legendFormat": "Maximum Connection Used"
    }
   ]
  },
  {
   "title": "MySQL Connection Error Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_connection_errors_total{host_name=\"$node_name\"}[5m])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "MySQL Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_threads{host_name=\"$node_name\", kind=\"connected\"}[5m])",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "rate(mysql_threads{host_name=\"$node_name\", kind=\"running\"}[5m])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "MySQL Query Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(__name__) (rate(mysql_query_count_total{host_name=\"$node_name\"}[5m]))",
     "legendFormat": "total query"
    },
    {
     "expr": "sum by(__name__) (rate(mysql_query_slow_count_total[5m]))",
     "legendFormat": "slow query"
    }
   ]
  },
  {
   "title": "MySQL Total Commands Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(command) (rate(mysql_commands_total{host_name=\"$node_name\"}[5m]))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "MySQL Table IO Operation Wait  Total  Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(mysql_table_io_wait_count_total{host_name=\"$node_name\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "MySQL Table IO Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(mysql_table_io_wait_time_nanoseconds_total{host_name=\"$node_name\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "MySQL Index IO Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(mysql_index_io_wait_time_nanoseconds_total{host_name=\"$node_name\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "MySQL Client Network IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mysql_client_network_io_bytes_total{host_name=\"$node_name\"}[5m])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "MySQL Buffer Pool Operations Total Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(mysql_buffer_pool_operations_total{host_name=\"$node_name\", operation=\"read_requests\"}[5m]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum by(operation) (rate(mysql_buffer_pool_operations_total{host_name=\"$node_name\", operation=\"write_requests\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "MySQL Buffer Pool Pages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum by(kind) (increase(mysql_buffer_pool_pages{host_name=\"$node_name\"}))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "MySQL Buffer Pool Pages Flush Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_buffer_pool_page_flushes_total{host_name=\"$node_name\"}[5m])",
     "legendFormat": "buffer pool pages flushes"
    },
    {}
   ]
  },
  {
   "title": "MySQL Buffer Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(status) (mysql_buffer_pool_usage_bytes{host_name=\"$node_name\"})",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "mysql_buffer_pool_limit_bytes{host_name=\"$node_name\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "MySQL Table Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(table) (mysql_table_size_bytes{host_name=\"$node_name\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "MySQL Table Rows Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(schema) (mysql_table_rows{host_name=\"$node_name\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "MySQL Table Lock Wait Read Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by(table) (rate(mysql_table_lock_wait_read_time_nanoseconds{host_name=\"$node_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Table Lock  Wait Write Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by(table) (rate(mysql_table_lock_wait_write_time_nanoseconds{host_name=\"$node_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}