{
 "title": "Nomad Cluster Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Nomad Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (host_name) (up{job=\"nomad_agent_metrics\"}))"
    }
   ]
  },
  {
   "title": "Nomad Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nomad_memberlist_size_local{vm_group=\"server\"})"
    }
   ]
  },
  {
   "title": "Total Running Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_summary_running{instance=\"localhost:4646\"})\r\n"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_status_running)"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_status_dead)"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_total_percent[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_memory_used)"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_disk_used_percent)"
    }
   ]
  },
  {
   "title": "tcp_sent_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "nomad_memberlist_tcp_sent_total",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "tcp_accept_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "nomad_memberlist_tcp_accept_total",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "tcp_connect_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "nomad_memberlist_tcp_connect_total",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": " Memory Utilization of the Nomad Agent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (nomad_runtime_alloc_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nomad Client Connection",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (nomad_nomad_heartbeat_active{vm_group=\"server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nomad  Allocation Running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (nomad_client_allocations_running{datacenter=\"dc1\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Nomad Job Status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_job_status_dead{vm_group=\"server\"}",
     "legendFormat": "Job Status Dead"
    },
    { "expr": "nomad_nomad_job_status_running", "legendFormat": "Job Status Running" },
    {
     "expr": "nomad_nomad_job_status_pending{host=\"nomad-srv3\"}",
     "legendFormat": "Job Status  Pending"
    }
   ]
  },
  {
   "title": "Number Of Evaluations",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (nomad_nomad_broker_total_ready{vm_group=\"server\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__name__) (nomad_nomad_broker_total_pending{vm_group=\"server\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__name__) (nomad_nomad_broker_total_unacked{vm_group=\"server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nomad Allocated Disk To Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(nomad_client_allocated_disk)",
     "legendFormat": "Allocated Disk"
    }
   ]
  },
  {
   "title": "Nomad  Allocated Memory To Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(__name__) (nomad_client_allocs_memory_allocated)",
     "legendFormat": "allocated memory"
    },
    {
     "expr": "sum(nomad_client_allocs_memory_rss)",
     "legendFormat": "used Memory"
    }
   ]
  },
  {
   "title": "Nomad allocated cpu to Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "sum by(__name__) (nomad_client_allocs_cpu_allocated)",
     "legendFormat": "Allocated CPU"
    },
    {}
   ]
  }
 ]
}