{
 "title": "Vcenter  Server Appliance  utilization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data Source",
    "query": "vmware-ariaoperations-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "MDC1-IT-Cloud-vCenter  Server File System Utilization %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "MDC1-ITM-VC01",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:VirtualMachine).name(\"mdc1-itm-vc01\").whereProperties(summary|parentVcenter = \"mdc1-itm\").metrics(guestfilesystem|percentage)"
    }
   ]
  },
  {
   "title": "MDC1-WLG-VC01",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:VirtualMachine).name(\"mdc1-wlg-vc01\").whereProperties(summary|parentVcenter = \"mdc1-itm\").metrics(guestfilesystem|percentage)"
    }
   ]
  },
  {
   "title": "MDC1-WLT-VC01",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:VirtualMachine).name(\"mdc1-wlt-vc01\").whereProperties(summary|parentVcenter = \"mdc1-itm\").metrics(guestfilesystem|percentage)"
    }
   ]
  },
  {
   "title": "MDC2-IT-Cloud-vCenter  Server File System Utilization %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "MDC2-ITM-VC01",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 328 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "resource(VMWARE:VirtualMachine).name(\"mdc2-itm-vc01\").whereProperties(summary|parentVcenter = \"mdc2-itm\").metrics(guestfilesystem|percentage)"
      }
     ]
    },
    {
     "title": "MDC2-WLG-VC01",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 464 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "resource(VMWARE:VirtualMachine).name(\"mdc2-wlg-vc01\").whereProperties(summary|parentVcenter = \"mdc2-itm\").metrics(guestfilesystem|percentage)"
      }
     ]
    },
    {
     "title": "MDC2-WLT-VC01",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 472 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "resource(VMWARE:VirtualMachine).name(\"mdc2-wlt-vc01\").whereProperties(summary|parentVcenter = \"mdc2-itm\").metrics(guestfilesystem|percentage)"
      }
     ]
    }
   ]
  },
  {
   "title": "MDC1-TCP vCenter Server File System Utilization %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "MDC1-TCPM-VC01",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "resource(VMWARE:VirtualMachine).name(\"mdc1-tcpm-vc01\").whereProperties(summary|parentVcenter = \"mdc1-tcpm-vc01.safaricomet.net\").metrics(guestfilesystem|percentage)"
      }
     ]
    },
    {
     "title": "MDC1-TCPC-VC01",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "resource(VMWARE:VirtualMachine).name(\"mdc1-tcpc-vc01\").whereProperties(summary|parentVcenter = \"mdc1-tcpm-vc01.safaricomet.net\").metrics(guestfilesystem|percentage)"
      }
     ]
    }
   ]
  },
  {
   "title": "MDC2-TCP vCenter  Server File System Utilization %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "MDC2-TCPM-VC01",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "resource(VMWARE:VirtualMachine).name(\"mdc2-tcpm-vc01.safaricomet.net\").whereProperties(summary|parentVcenter = \"mdc2-tcpm-vc01.safaricomet.net\").metrics(guestfilesystem|percentage)"
      }
     ]
    },
    {
     "title": "MDC2-TCPC-VC01",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "resource(VMWARE:VirtualMachine).name(\"mdc2-tcpc-vc01.safaricomet.net\").whereProperties(summary|parentVcenter = \"mdc2-tcpm-vc01.safaricomet.net\").metrics(guestfilesystem|percentage)"
      }
     ]
    }
   ]
  }
 ]
}