{
 "title": "vCenter VM Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "vcenter_cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(vcenter_cluster_host_count,vcenter_cluster_name)"
    }
   },
   {
    "name": "vcenter_vm",
    "label": "VM Name",
    "query": {
     "query": "label_values(vcenter_vm_cpu_utilization_percent{vcenter_cluster_name=\"$vcenter_cluster\"},vcenter_vm_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcenter_vm_cpu_utilization_percent{vcenter_vm_name=~\"$vcenter_vm\"}",
     "legendFormat": "{{vcenter_vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcenter_vm_memory_utilization_percent{vcenter_vm_name=~\"$vcenter_vm\"}",
     "legendFormat": "{{vcenter_vm_name}}"
    }
   ]
  },
  {
   "title": "vSAN Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "vcenter_vm_vsan_throughput_bytes_per_second{vcenter_vm_name=~\"$vcenter_vm\"}",
     "legendFormat": "{{vcenter_vm_name}} - {{direction}}"
    }
   ]
  },
  {
   "title": "vSAN IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "vcenter_vm_vsan_operations{vcenter_vm_name=~\"$vcenter_vm\"}",
     "legendFormat": "{{vcenter_vm_name}} - {{type}}"
    }
   ]
  },
  {
   "title": "vSAN Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "vcenter_vm_vsan_latency_avg_microseconds{vcenter_vm_name=~\"$vcenter_vm\"}",
     "legendFormat": "{{vcenter_vm_name}} - {{type}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcenter_vm_disk_utilization_percent{vcenter_vm_name=~\"$vcenter_vm\"}",
     "legendFormat": "{{vcenter_vm_name}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "vcenter_vm_network_usage{vcenter_vm_name=~\"$vcenter_vm\",object=\"\"} * 8",
     "legendFormat": "{{vcenter_vm_name}}"
    }
   ]
  },
  {
   "title": "Network Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "vcenter_vm_network_packet_rate{vcenter_vm_name=~\"$vcenter_vm\",direction=\"received\",object=~\"4.+\"}",
     "legendFormat": "{{vcenter_vm_name}} {{object}} {{direction}}"
    },
    {
     "expr": "1- vcenter_vm_network_packet_rate{vcenter_vm_name=~\"$vcenter_vm\",direction=\"transmitted\",object=~\"4.+\"}",
     "legendFormat": "{{vcenter_vm_name}} {{object}} {{direction}}"
    }
   ]
  }
 ]
}