{
 "title": "vCenter Host Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "vcenter_cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(vcenter_cluster_name)"
    }
   },
   {
    "name": "vcenter_host",
    "label": "ESXi Host",
    "query": {
     "query": "label_values({vcenter_cluster_name=\"$vcenter_cluster\"},vcenter_host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Power On VM Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vcenter_cluster_vm_count{vcenter_cluster_name=\"$vcenter_cluster\", power_state=\"on\"}",
     "legendFormat": "Powered On"
    }
   ]
  },
  {
   "title": "Power Off VM Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vcenter_cluster_vm_count{vcenter_cluster_name=\"$vcenter_cluster\", power_state=\"off\"}",
     "legendFormat": "Powered Off"
    }
   ]
  },
  {
   "title": "Suspended VM Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vcenter_cluster_vm_count{vcenter_cluster_name=\"$vcenter_cluster\", power_state=\"suspended\"}",
     "legendFormat": "Suspended"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcenter_host_cpu_utilization_percent{vcenter_host_name=~\"$vcenter_host\"}",
     "legendFormat": "{{vcenter_host_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcenter_host_memory_utilization_percent{vcenter_host_name=~\"$vcenter_host\"}",
     "legendFormat": "{{vcenter_host_name}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "vcenter_host_network_usage{vcenter_host_name=~\"$vcenter_host\", object=~\"vmnic.*\"} * 8",
     "legendFormat": "{{vcenter_host_name}} - {{object}}"
    }
   ]
  },
  {
   "title": "Network Packet Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(object, vcenter_host_name) (vcenter_host_network_packet_drop_rate{vcenter_host_name=~\"$vcenter_host\", object=~\"vmnic.*\"})",
     "legendFormat": "{{vcenter_host_name}} - {{object}}"
    }
   ]
  },
  {
   "title": "Network Packet Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(object, vcenter_host_name) (vcenter_host_network_packet_error_rate{vcenter_host_name=~\"$vcenter_host\", object=~\"vmnic.*\"})",
     "legendFormat": "{{vcenter_host_name}} - {{object}}"
    }
   ]
  },
  {
   "title": "vSAN Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "vcenter_host_vsan_throughput_bytes_per_second{vcenter_host_name=~\"$vcenter_host\"}",
     "legendFormat": "{{vcenter_host_name}} - {{direction}}"
    }
   ]
  },
  {
   "title": "vSAN IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "vcenter_host_vsan_operations{vcenter_host_name=~\"$vcenter_host\"}",
     "legendFormat": "{{vcenter_host_name}} - {{type}}"
    }
   ]
  },
  {
   "title": "vSAN Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "vcenter_host_vsan_latency_avg_microseconds{vcenter_host_name=~\"$vcenter_host\"}",
     "legendFormat": "{{vcenter_host_name}} - {{type}}"
    }
   ]
  }
 ]
}