{
 "title": "vCenter Cluster Status (vROps)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data Source",
    "query": "vmware-ariaoperations-datasource"
   },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "resource(`VMWARE:VMwareAdapter Instance`).all()"
    }
   },
   {
    "name": "dc",
    "label": "DC",
    "query": {
     "query": "resource(VMWARE:Datacenter).whereProperties(summary|parentVcenter = \"$${vcenter}\")"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "resource(VMWARE:ClusterComputeResource).\r\n    whereProperties(summary|parentDatacenter = \"$${dc}\" and summary|parentVcenter = \"$${vcenter}\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datacenter).name(\"$${dc}\").whereProperties(summary|parentVcenter = \"$${vcenter}\").metrics(summary|total_number_clusters)"
    }
   ]
  },
  {
   "title": "Host Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datacenter).name(\"$${dc}\").whereProperties(summary|parentVcenter = \"$${vcenter}\").metrics(summary|total_number_hosts)"
    }
   ]
  },
  {
   "title": "VM Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datacenter).name(\"$${dc}\").whereProperties(summary|parentVcenter = \"$${vcenter}\").metrics(summary|total_number_vms)"
    }
   ]
  },
  {
   "title": "VM Template Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datacenter).name(\"$${dc}\").whereProperties(summary|parentVcenter = \"$${vcenter}\").metrics(summary|number_vm_templates)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"$${cluster}\").metrics(cpu|capacity_usagepct_average)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"$${cluster}\").metrics(mem|usage_average)"
    }
   ]
  },
  {
   "title": "Datastore Utilization",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datastore).\r\n    whereProperties(summary|parentDatacenter = \"$${dc}\" and summary|isLocal = \"false\" and summary|type = \"vsan\").\r\n    metrics(capacity|usedSpacePct)"
    }
   ]
  },
  {
   "title": "vSAN Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datastore).\r\n    whereProperties(summary|parentVcenter = \"$${vcenter}\" and summary|parentDatacenter = \"$${dc}\" and summary|type = \"vsan\").\r\n    metrics(datastore|totalReadLatency_average)"
    },
    {
     "queryText": "resource(VMWARE:Datastore).\r\n    whereProperties(summary|parentDatacenter = \"$${dc}\" and summary|type = \"vsan\").\r\n    metrics(datastore|totalWriteLatency_average)"
    }
   ]
  },
  {
   "title": "vSAN IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datastore).\r\n    whereProperties(summary|parentVcenter = \"$${vcenter}\" and summary|parentDatacenter = \"$${dc}\" and summary|type = \"vsan\").\r\n    metrics(datastore|numberReadAveraged_average)"
    },
    {
     "queryText": "resource(VMWARE:Datastore).\r\n    whereProperties(summary|parentDatacenter = \"$${dc}\" and summary|type = \"vsan\").\r\n    metrics(datastore|numberWriteAveraged_average)"
    }
   ]
  },
  {
   "title": "vSAN Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datastore).\r\n    whereProperties(summary|parentVcenter = \"$${vcenter}\" and summary|parentDatacenter = \"$${dc}\" and summary|type = \"vsan\").\r\n    metrics(datastore|read_average)"
    },
    {
     "queryText": "resource(VMWARE:Datastore).\r\n    whereProperties(summary|parentDatacenter = \"$${dc}\" and summary|type = \"vsan\").\r\n    metrics(datastore|write_average)"
    }
   ]
  }
 ]
}