apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external-secrets.yaml
configMapGenerator:
- files:
  - values.yaml=helm-values/external-secrets.yaml
  name: external-secrets-values
  namespace: external-secrets
  options:
    disableNameSuffixHash: true
