{
 "title": "CoreDNS",
 "description": "This is a modern CoreDNS dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(up{job=~\".+coredns|coredns\"},k8s_cluster_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$$job\", k8s_cluster_name=\"$$cluster\"},instance)"
    }
   },
   {
    "name": "protocol",
    "query": {
     "query": "label_values(coredns_dns_requests_total{k8s_cluster_name=\"$$cluster\"},proto)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job",
    "query": {
     "query": "label_values(coredns_build_info{k8s_cluster_name=\"$$cluster\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CoreDNS - Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$$job\", instance=~\"$$instance\", k8s_cluster_name=~\"$$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CoreDNS - CPU Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$$job\", instance=~\"$$instance\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Memory Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$$job\", instance=~\"$$instance\", k8s_cluster_name=~\"$$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Total DNS Requests ($protocol)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$$instance\",proto=\"$$protocol\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval]))",
     "legendFormat": "total $protocol requests"
    }
   ]
  },
  {
   "title": "CoreDNS - Average Packet Size  ($protocol)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_size_bytes_sum{instance=~\"$$instance\",proto=\"$$protocol\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])) by (proto) / sum(rate(coredns_dns_request_size_bytes_count{instance=~\"$$instance\",proto=\"$$protocol\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])) by (proto)",
     "legendFormat": "average $protocol packet size"
    }
   ]
  },
  {
   "title": "CoreDNS - Requests by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$$instance\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Requests by return code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$$instance\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Total Forward Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{k8s_cluster_name=~\"$$cluster\"}[$__rate_interval]))",
     "legendFormat": "total forward requests"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_responses_total{rcode=~\"SERVFAIL|REFUSED\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Cache Hits / Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$$instance\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{instance=~\"$$instance\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])) by (type)",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "CoreDNS - Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{k8s_cluster_name=~\"$$cluster\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS request duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_request_duration_seconds_bucket{instance=~\"$$instance\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS request size",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_request_size_bytes_bucket{instance=~\"$$instance\", le!=\"0\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS response size",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_response_size_bytes_bucket{instance=~\"$$instance\", le!=\"0\", k8s_cluster_name=~\"$$cluster\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}