{
 "title": "Envoy Proxy",
 "description": "Envoy proxy monitoring Dashboard with cluster and host level templates. ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_active,k8s_cluster_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{k8s_cluster_name=\"$cluster_name\", envoy_cluster_name!~\"contour.+|extension.+\"},envoy_cluster_name)"
    }
   },
   {
    "name": "hosts",
    "label": "Hosts",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{envoy_cluster_name=\"$cluster\", k8s_cluster_name=\"$cluster_name\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{k8s_cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{k8s_cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_memory_allocated{k8s_cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_memory_heap_size{k8s_cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy{k8s_cluster_name=\"$cluster_name\"})  - sum(envoy_cluster_membership_total{k8s_cluster_name=\"$cluster_name\"}))"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{k8s_cluster_name=\"$cluster_name\"})-sum(envoy_cluster_membership_healthy{k8s_cluster_name=\"$cluster_name\"})) == bool 0"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$cluster\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"}) by (host_name)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"}[1m])) by (host_name)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Downstream Total active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=~\"ingress.+\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"}) by (host_name)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Downstream Total active requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=~\"ingress.+\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"}[1m])) by (host_name)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Upstream Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$cluster\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"}[1m])) by (host_name)",
     "legendFormat": "{{host_name}} - in"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=~\"$cluster\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"}[1m])) by (host_name)",
     "legendFormat": "{{host_name}} - out"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"ingress.+\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"}[1m])) by (host_name)",
     "legendFormat": "{{host_name}} - in"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"ingress.+\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"}[1m])) by (host_name)",
     "legendFormat": "{{host_name}} - out"
    }
   ]
  },
  {
   "title": "Downstream members",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"})/count(envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"})",
     "legendFormat": "healthy"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"})/count(envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\",host_name=~\"$hosts\",k8s_cluster_name=\"$cluster_name\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}