{
 "title": "Etcd Cluster Overview",
 "description": "Etcd Cluster Overview showing details scraped from the etcd Prometheus metrics endpoint.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(etcd_cluster_version{k8s_namespace_name=\"kube-system\"},job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(etcd_server_version{job=\"$job\", k8s_namespace_name=\"kube-system\"},k8s_cluster_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(etcd_server_version{job=\"$job\", k8s_cluster_name=\"$cluster\", k8s_namespace_name=\"kube-system\", instance!=\"127.0.0.1:2381\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "15s,1m,5m,10m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Has Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"})",
     "legendFormat": "Has Leader"
    }
   ]
  },
  {
   "title": "Members",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_id{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"})",
     "legendFormat": "Members"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"})*100"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_keys_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}) by (instance)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "sum(etcd_server_is_leader{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}) by (instance)"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_db_compaction_keys_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}) by (instance)"
    },
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"})*100",
     "legendFormat": "Urgent Defragmentation"
    },
    {
     "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"} - etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}",
     "legendFormat": "DB Capacity"
    },
    {
     "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}"
    },
    {
     "expr": "etcd_server_version{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Leader Changes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"})",
     "legendFormat": "Leader Changes"
    }
   ]
  },
  {
   "title": "Failed Proposals",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"})",
     "legendFormat": "Failed Proposals"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Client Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Keys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Keys (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_keys_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Key Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_put_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} puts/s"
    },
    {
     "expr": "rate(etcd_debugging_mvcc_delete_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} deletes/s"
    }
   ]
  },
  {
   "title": "Compaction Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_compaction_keys_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance  }}"
    }
   ]
  },
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DB Total Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} Total Size"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} In Use"
    }
   ]
  },
  {
   "title": "Disks Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_fsync_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }} WAL fsync"
    },
    {
     "expr": "rate(etcd_disk_backend_commit_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }} backend commit"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{ instance }} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{ instance }} DB fsync"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_server_heartbeat_send_failures_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} heartbeat  failures"
    },
    {
     "expr": "etcd_server_health_failures{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} health failures"
    }
   ]
  },
  {
   "title": "Slow Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_server_slow_apply_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} Slow Applies"
    },
    {
     "expr": "etcd_server_slow_read_indexes_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ instance }} Slow Read Indexes"
    }
   ]
  },
  {
   "title": "Defrag Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_disk_backend_defrag_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "timeseries",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[1m]))",
     "legendFormat": "The Total Latency Distributions of Save Called by Snapshot"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "Compaction Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_db_compaction_keys_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} compact/s"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[1d])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Proposals Pending",
   "type": "timeseries",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"})",
     "legendFormat": "Proposals Pending"
    }
   ]
  },
  {
   "title": "The Total Number of Consensus Proposals Committed",
   "type": "timeseries",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "Total Applied"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "GRPC Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{instance=~\"$instance\",job=~\"$job\",k8s_cluster_name=\"$cluster\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}