{
 "title": "High Level Cluster Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Ready",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(k8s_cluster_name) (k8s_node_condition{condition=\"Ready\"}) / count by(k8s_cluster_name) (system_uptime_seconds)",
     "legendFormat": "{{k8s_cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster PID Pressure",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by(k8s_cluster_name) (k8s_node_condition{condition=\"PIDPressure\"}) / count by(k8s_cluster_name) (system_uptime_seconds)",
     "legendFormat": "{{k8s_cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Disk Pressure",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(k8s_cluster_name) (k8s_node_condition{condition=\"DiskPressure\"}) / count by(k8s_cluster_name) (system_uptime_seconds)",
     "legendFormat": "{{k8s_cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Pressure",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by(k8s_cluster_name) (k8s_node_condition{condition=\"MemoryPressure\"}) / count by(k8s_cluster_name) (system_uptime_seconds)",
     "legendFormat": "{{k8s_cluster_name}}"
    }
   ]
  },
  {
   "title": "Physical Server Health",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "idrac_system_health * on(instance) group_left(hostname) idrac_system_machine_info > 0",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "idrac_system_power_on * on(instance) group_left(hostname) idrac_system_machine_info == 0",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Expiring Certificate < 45 days",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "(label_join(sum by (k8s_cluster_name,target) (probe_ssl_earliest_cert_expiry{k8s_cluster_name!=\"\"}), \"location\", \"-\", \"k8s_cluster_name\",\"target\") - time())/ 86400 < 45",
     "legendFormat": "{{target}} in {{k8s_cluster_name}}"
    },
    {
     "expr": "(label_join(sum by (k8s_cluster_name,target) (probe_success{k8s_cluster_name!=\"\"}), \"location\", \"-\", \"k8s_cluster_name\",\"target\") - 201) == -201",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "PVC Usage > 75%",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "(1 - (avg by (k8s_persistentvolumeclaim_name,k8s_cluster_name) (k8s_volume_available_bytes{k8s_volume_type=\"persistentVolumeClaim\"}) / avg by (k8s_persistentvolumeclaim_name,k8s_cluster_name) (k8s_volume_capacity_bytes{k8s_volume_type=\"persistentVolumeClaim\"}))) > 0.75",
     "legendFormat": "{{k8s_persistentvolumeclaim_name}} in {{k8s_cluster_name}}"
    }
   ]
  },
  {
   "title": "Kubernetes Nodes Free Memory  < 500MiB",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "sum(k8s_node_memory_available_bytes) by (k8s_node_name) < 500000000",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "Kubernetes Nodes CPU > 75%",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "(k8s_node_cpu_utilization_ratio{} / system_cpu_physical_count{}) > 0.75",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  }
 ]
}