{
 "title": "Kubernetes Cluster Statistics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(k8s_pod_phase,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(k8s_pod_phase{k8s_cluster_name=~\"$cluster_name\"},k8s_namespace_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(k8s_pod_cpu_usage{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})/sum(system_cpu_physical_count{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "CPU Usage %"
    },
    {
     "expr": "sum(k8s_pod_cpu_usage{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "CPU Core Consumed"
    }
   ]
  },
  {
   "title": "Memory Utilization for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(k8s_pod_memory_working_set_bytes{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})/sum(system_memory_limit_bytes{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "Memory Usage %"
    },
    {
     "expr": "sum(k8s_pod_memory_working_set_bytes{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "Memory Consumed"
    }
   ]
  },
  {
   "title": "Network Utilization for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "1- sum(rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\",direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "Network Received"
    },
    {
     "expr": "sum(rate(k8s_pod_network_io_bytes_total{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\",direction=\"transmit\"}[$__rate_interval]))",
     "legendFormat": "Network Transmited"
    }
   ]
  },
  {
   "title": "CPU Usage % for $namespace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_pod_cpu_usage{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})/sum(system_cpu_physical_count{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores Consumed for $namespace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_pod_cpu_usage{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage % for $namespace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_pod_memory_working_set_bytes{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})/sum(system_memory_limit_bytes{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Consumed for $namespace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_pod_memory_working_set_bytes{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_node_condition{k8s_cluster_name=~\"$cluster_name\",condition=\"Ready\",k8s_node_name=~\".+control.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_node_condition{k8s_cluster_name=~\"$cluster_name\",condition=\"Ready\",k8s_node_name=~\".+np-01.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_namespace_phase{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Resource Count for $namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_deployment_desired{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "StatefulSet Resource Count for $namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_statefulset_desired_pods{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonSet Resource Count for $namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_daemonset_desired_scheduled_nodes{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Resource Count for $namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_job_desired_successful_pods{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HPA Count for $namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_hpa_desired_replicas{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Count for $namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_volume_available_bytes{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\",k8s_volume_type=\"persistentVolumeClaim\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Count for $namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_pod_phase{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Count for $namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_container_ready{k8s_cluster_name=~\"$cluster_name\",k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}