{
 "title": "Node Details",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(system_uptime_seconds,k8s_cluster_name)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(system_uptime_seconds{k8s_cluster_name=\"$cluster\"},k8s_node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Condition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_node_condition{k8s_cluster_name=\"$cluster\", k8s_node_name=\"$node_name\",condition=\"Ready\"}",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "k8s_node_condition{k8s_cluster_name=\"$cluster\", k8s_node_name=\"$node_name\",condition=\"DiskPressure\"}",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "k8s_node_condition{k8s_cluster_name=\"$cluster\", k8s_node_name=\"$node_name\",condition=\"MemoryPressure\"}",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "k8s_node_condition{k8s_cluster_name=\"$cluster\", k8s_node_name=\"$node_name\",condition=\"PIDPressure\"}",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime_seconds{k8s_node_name=\"$node_name\"}",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "Kubelet Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_node_allocatable_cpu{k8s_node_name=\"$node_name\"}",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "Container Runtime Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_node_allocatable_cpu{k8s_node_name=\"$node_name\"}",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "OS Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "targets": [
    {
     "expr": "k8s_node_condition_ready{k8s_cluster_name=\"$cluster\", k8s_node_name=\"$node_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kernel Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "scrape_series_added{k8s_cluster_name=\"$cluster\", k8s_node_name=\"$node_name\", service_name=\"otel-agent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_physical_count{k8s_node_name=\"$node_name\"}",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_limit_bytes{k8s_node_name=\"$node_name\"}",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "Processes Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_processes_count{k8s_node_name=\"$node_name\"})",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage % per CPU State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(system_cpu_utilization_ratio{k8s_node_name=\"$node_name\", state!=\"idle\"}) by (state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage % per CPU Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cpu) (system_cpu_utilization_ratio{k8s_node_name=\"$node_name\", state!=\"idle\"})",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(state) (system_memory_usage_bytes{k8s_node_name=\"$node_name\", state!=\"free\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total{k8s_node_name=\"$node_name\", device=\"eth0\",direction=\"receive\"}[$__rate_interval]) * 8",
     "legendFormat": "{{direction}}"
    },
    {
     "expr": "1-rate(system_network_io_bytes_total{k8s_node_name=\"$node_name\", device=\"eth0\",direction=\"transmit\"}[$__rate_interval]) * 8",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_filesystem_utilization_ratio{k8s_node_name=\"$node_name\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(system_disk_io_bytes_total{k8s_node_name=\"$node_name\", device=~\"...\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Network Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(system_network_packets_total{k8s_node_name=\"$node_name\", device=\"eth0\",direction=\"transmit\"}[$__rate_interval])",
     "legendFormat": "{{direction}}"
    },
    {
     "expr": "1-rate(system_network_packets_total{k8s_node_name=\"$node_name\", device=\"eth0\",direction=\"receive\"}[$__rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(system_disk_operations_total{k8s_node_name=\"$node_name\", device=~\"...\"}[$__rate_interval])",
     "legendFormat": "{{device}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Network Packet Drop & Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(system_network_dropped_total{k8s_node_name=\"$node_name\", device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "Dropped - {{direction}}"
    },
    {
     "expr": "rate(system_network_errors_total{k8s_node_name=\"$node_name\", device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "Error - {{direction}}"
    }
   ]
  },
  {
   "title": "Network Connection State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "system_network_connections{k8s_node_name=\"$node_name\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Disk IO Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "system_disk_pending_operations{k8s_node_name=\"$node_name\", device=~\"...\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}