{
 "title": "Pod Details",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(container_uptime_seconds_total,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_uptime_seconds_total{k8s_cluster_name=~\"$cluster_name\"},k8s_namespace_name)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(container_uptime_seconds_total{k8s_cluster_name=~\"$cluster_name\"},k8s_node_name)"
    }
   },
   {
    "name": "pod_name",
    "label": "Pod Name",
    "query": {
     "query": "query_result(sum(k8s_pod_phase{k8s_cluster_name=\"$cluster_name\",k8s_namespace_name=~\"$namespace\",k8s_node_name=~\"$node_name\"} == 2) by (k8s_pod_name))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_container_ready{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"})",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_pod_uptime_seconds_total{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Phase",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_pod_phase{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1- (k8s_volume_available_bytes{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\", k8s_volume_type=\"persistentVolumeClaim\"} / k8s_volume_capacity_bytes{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\", k8s_volume_type=\"persistentVolumeClaim\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores Consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_pod_cpu_usage{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_pod_memory_working_set_bytes{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Network Received Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(k8s_pod_network_io_bytes_total{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\", direction=\"receive\"}[$__rate_interval])",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Network Transmited Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(k8s_pod_network_io_bytes_total{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\", direction=\"transmit\"}[$__rate_interval])",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Request Recommendation (milli-cores)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "p99" ] } },
   "targets": [
    {
     "expr": "quantile(0.99, container_cpu_usage{k8s_cluster_name=\"$cluster_name\",k8s_pod_name=\"$pod_name\"}) by (k8s_container_name) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Request Recommendation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "p99" ] } },
   "targets": [
    {
     "expr": "quantile(0.99, container_memory_working_set_bytes{k8s_cluster_name=\"$cluster_name\",k8s_pod_name=\"$pod_name\"}) by (k8s_container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "k8s_container_cpu_limit_utilization_ratio{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "{{k8s_container_name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "k8s_container_memory_limit_utilization_ratio{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "{{k8s_container_name}}"
    }
   ]
  },
  {
   "title": "Pod Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(k8s_pod_network_io_bytes_total{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}[$__rate_interval])",
     "legendFormat": "{{k8s_pod_name}} - {{direction}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "k8s_container_cpu_limit{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k8s_container_cpu_request{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k8s_container_memory_limit_bytes{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k8s_container_memory_request_bytes{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k8s_container_ready{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k8s_container_restarts{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_uptime_seconds_total{k8s_pod_name=\"$pod_name\", k8s_cluster_name=\"$cluster_name\", k8s_namespace_name=~\"$namespace\", k8s_node_name=~\"$node_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{k8s.cluster.name=\"$cluster_name\",k8s.pod.name=\"$pod_name\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}