apiVersion: v1
kind: Namespace
metadata:
  name: alertmanager
  labels:
    pod-security.kubernetes.io/enforce: privileged
    kyverno.io/exclude-rule: "true"
spec: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: eda-webhook-token
  namespace: alertmanager
stringData:
  webhook-token: ${webhook_token}
  webhook-url: ${webhook_url}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: alertmanager
spec:
  interval: 1m
  timeout: 40m
  chart:
    spec:
      chart: alertmanager
      version: 1.27.1
      sourceRef:
        kind: HelmRepository
        name: local-harbor-helm-repo
        namespace: flux-system
      interval: 5m
  releaseName: alertmanager
  dependsOn:
    - name: kyverno
      namespace: kyverno
  valuesFrom:
    - kind: ConfigMap
      name: alertmanager-values
  postRenderers:
    - kustomize:
        images:
          - name: quay.io/prometheus-operator/prometheus-config-reloader:v0.86.1
            newName: ${registry_host}/platform/alertmanager-images
            digest: sha256:sha256:23cf848a56ae37bd1ed4ea9c0eb787d50b0bfd5f71c30e2d5f380f424d5dfadb
          - name: quay.io/prometheus/alertmanager:v0.28.1
            newName: ${registry_host}/platform/alertmanager-images
            digest: sha256:sha256:f151ee742370e67875ab275e2d5289ad205cc7a544e2306311f5a3c3fb579465
