apiVersion: v1
kind: Namespace
metadata:
  name: postgresql-ha
  labels:
    pod-security.kubernetes.io/enforce: privileged
    kyverno.io/exclude-rule: "true"
spec: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql-ha
  namespace: postgresql-ha
spec:
  interval: 1m
  timeout: 40m
  chart:
    spec:
      chart: postgresql-ha
      version: 14.3.6
      sourceRef:
        kind: HelmRepository
        name: local-harbor-helm-repo
        namespace: flux-system
      interval: 5m
  releaseName: postgresql-ha
  dependsOn:
  - name: kyverno
    namespace: kyverno
  - name: kube-prometheus
    namespace: kube-prometheus
  valuesFrom:
  - kind: ConfigMap
    name: postgresql-ha-values
  postRenderers:
  - kustomize:
      images:
      - name: docker.io/bitnami/os-shell:12-debian-12-r31
        newName: ${registry_host}/platform/postgresql-ha-images
        digest: sha256:b0de135047b5fb11944a3a3816ad74c699e79ce6f9ebcf4cee3211e1b6aa7c90
      - name: docker.io/bitnami/pgpool:4.5.4-debian-12-r2
        newName: ${registry_host}/platform/postgresql-ha-images
        digest: sha256:cd7e4ca1b70097ad842e99c343f1d66dd2320a1927c4970304dc6c06b997d428
      - name: docker.io/bitnami/postgres-exporter:0.15.0-debian-12-r44
        newName: ${registry_host}/platform/postgresql-ha-images
        digest: sha256:119e0dedbdf0784420b40a2260305f0f9ac3418180a65386291635d9aa8dae87
      - name: docker.io/bitnami/postgresql-repmgr:16.4.0-debian-12-r27
        newName: ${registry_host}/platform/postgresql-ha-images
        digest: sha256:23d89f59aba2f17cb7e08c58c7a8d5acd54805f18644507266e827e6fccc98b5
