apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmalert
  namespace: victoria-logs
spec:
  interval: 1m
  timeout: 40m
  chart:
    spec:
      chart: victoria-metrics-alert
      version: 0.25.5
      sourceRef:
        kind: HelmRepository
        name: local-harbor-helm-repo
        namespace: flux-system
      interval: 5m
  releaseName: vmalert
  dependsOn:
  - name: kyverno
    namespace: kyverno
  - name: victoria-metrics
    namespace: victoria-metrics
  - name: vma
    namespace: victoria-logs
  - name: alertmanager
    namespace: alertmanager
  valuesFrom:
  - kind: ConfigMap
    name: victoria-logs-vmalert-values
  postRenderers:
  - kustomize:
      images:
      - name: victoriametrics/vmalert:v1.126.0
        newName: ${registry_host}/platform/victoria-metrics-alert-images
        digest: sha256:addc28679f146199c048f571aededcdde362394a862b6ab8b19d65f02e6ed3bb
