apiVersion: v1
kind: Namespace
metadata:
  name: victoria-metrics
  labels:
    pod-security.kubernetes.io/enforce: privileged
    kyverno.io/exclude-rule: "true"
spec: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: victoria-metrics
spec:
  interval: 1m
  timeout: 40m
  chart:
    spec:
      chart: victoria-metrics-cluster
      version: 0.28.4
      sourceRef:
        kind: HelmRepository
        name: local-harbor-helm-repo
        namespace: flux-system
      interval: 5m
  releaseName: victoria-metrics
  dependsOn:
  - name: kyverno
    namespace: kyverno
  - name: kube-prometheus
    namespace: kube-prometheus
  valuesFrom:
  - kind: ConfigMap
    name: victoria-metrics-values
  postRenderers:
  - kustomize:
      images:
      - name: victoriametrics/vminsert:v1.126.0-cluster
        newName: ${registry_host}/platform/victoria-metrics-cluster-images
        digest: sha256:df9f52bc8391498bdb6b2e6ccd0735ddaeefe6c8cc352d5947068056c8f157c5
      - name: victoriametrics/vmselect:v1.126.0-cluster
        newName: ${registry_host}/platform/victoria-metrics-cluster-images
        digest: sha256:cb6c16067a1714ffc2611ef31ea124f5fa79d556bb4b6eb80f04eb01042e8e6f
      - name: victoriametrics/vmstorage:v1.126.0-cluster
        newName: ${registry_host}/platform/victoria-metrics-cluster-images
        digest: sha256:04b59bb5012c8fda15a15f2e736c8e8d7b5719ba2780d49f4be9dfd8c117d4cd
