apiVersion: v1
kind: Namespace
metadata:
  name: victoria-logs
  labels:
    pod-security.kubernetes.io/enforce: privileged
    kyverno.io/exclude-rule: "true"
spec: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vlc1
  namespace: victoria-logs
spec:
  interval: 1m
  timeout: 40m
  chart:
    spec:
      chart: victoria-logs-cluster
      version: 0.0.11
      sourceRef:
        kind: HelmRepository
        name: local-harbor-helm-repo
        namespace: flux-system
      interval: 5m
  releaseName: vlc1
  dependsOn:
  - name: kyverno
    namespace: kyverno
  - name: kube-prometheus
    namespace: kube-prometheus
  valuesFrom:
  - kind: ConfigMap
    name: victoria-logs-values
  postRenderers:
  - kustomize:
      images:
      - name: victoriametrics/victoria-logs:v1.33.0
        newName: ${registry_host}/platform/victoria-logs-cluster-images
        digest: sha256:sha256:2dac59f4a3ca4a2ecd0db90d87bf994562ec2a04bfec9771bb8760673e8c88ea
