apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vma
  namespace: victoria-logs
spec:
  interval: 1m
  timeout: 40m
  chart:
    spec:
      chart: victoria-metrics-auth
      version: 0.19.5
      sourceRef:
        kind: HelmRepository
        name: local-harbor-helm-repo
        namespace: flux-system
      interval: 5m
  releaseName: vma
  dependsOn:
  - name: kyverno
    namespace: kyverno
  - name: kube-prometheus
    namespace: kube-prometheus
  - name: vlc2
    namespace: victoria-logs
  valuesFrom:
  - kind: ConfigMap
    name: victoria-metrics-auth-values
  postRenderers:
  - kustomize:
      images:
      - name: victoriametrics/vmauth:v1.126.0
        newName: ${registry_host}/platform/victoria-metrics-auth-images
        digest: sha256:sha256:9fcf83d31072e87af326d3dd1c6847cb5a28845392e661ea9c4e27648b9ea5e9
