{
 "title": "Service Stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{http_status_code!=\"0\", service!=\"contour\"},k8s_cluster_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{k8s_cluster_name=\"$cluster_name\", span_kind=\"SPAN_KIND_SERVER\", http_method!~\"\", service!=\"contour\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service) (rate(traces_spanmetrics_calls_total{k8s_cluster_name=\"$cluster_name\", service=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Success Rate %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (rate(traces_spanmetrics_calls_total{k8s_cluster_name=\"$cluster_name\", service=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", http_status_code!~\"5.*|404|405|42.\"}[1m])) / sum by(service) (rate(traces_spanmetrics_calls_total{k8s_cluster_name=\"$cluster_name\", service=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Service Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 24, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "limit": 20,
     "query": "{resource.service.name=\"$service_name\"}",
     "serviceMapQuery": "{k8s_cluster_name=\"$cluster_name\",service_name=\"$service_name\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service) (rate(traces_spanmetrics_calls_total{k8s_cluster_name=\"$cluster_name\", service=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"5.*|404|405|42.\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (rate(traces_spanmetrics_calls_total{k8s_cluster_name=\"$cluster_name\", service=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"5.*|404|405|42.\"}[1m])) / sum by(service) (rate(traces_spanmetrics_calls_total{k8s_cluster_name=\"$cluster_name\", service=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(traces_spanmetrics_latency_bucket{k8s_cluster_name=\"$cluster_name\", service=\"$service_name\"}[1m])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(traces_spanmetrics_latency_bucket{k8s_cluster_name=\"$cluster_name\", service=\"$service_name\"}[1m])))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(traces_spanmetrics_latency_bucket{k8s_cluster_name=\"$cluster_name\", service=\"$service_name\"}[1m])))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "HTTP Status Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{k8s_cluster_name=\"$cluster_name\", service=\"$service_name\", span_kind=\"SPAN_KIND_SERVER\", http_status_code!=\"0\"}[1m]))",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  }
 ]
}