{
 "title": "Physical Server Details",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "server_name",
    "label": "Server",
    "query": {
     "query": "label_values(idrac_system_machine_info,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_health * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_power_on * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iDRAC IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_cpu_count * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Tag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Socket Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_cpu_count * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_memory_size_bytes * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_cpu_count * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BIOS Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_system_bios_info * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(idrac_cpu_total_cores * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drive Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(idrac_storage_drive_capacity_bytes  * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Drives",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "idrac_storage_drive_capacity_bytes * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}  * on(id,instance) group_right(hostname) idrac_storage_drive_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_storage_drive_health * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_storage_drive_life_left_percent * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "idrac_memory_module_capacity_bytes * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}  * on(id,instance) group_right(hostname) idrac_memory_module_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_memory_module_health * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Controller",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "idrac_storage_controller_health * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}  * on(id,instance) group_right(hostname) idrac_storage_controller_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_storage_controller_speed_mbps * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Supply Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "idrac_power_supply_capacity_watts * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_power_supply_efficiency_percent * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_power_supply_health * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_power_supply_input_voltage * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_power_supply_input_watts * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_power_supply_output_watts * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Status",
   "type": "table",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "idrac_sensors_fan_health * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_sensors_fan_speed * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Port Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "expr": "idrac_network_port_health * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_network_port_link_up * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_network_port_current_speed_mbps * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idrac_network_adapter_info * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_sensors_temperature * on(instance) group_left(hostname) idrac_system_machine_info{hostname=\"$server_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}