{
 "title": "PowerScale Protocol Detail",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cluster_node_count_all_value,cluster)"
    }
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Protocols",
    "label": "Protocols",
    "query": "nfs,nfs4,nfsrdma,smb1,smb2,hdfs,ftp,siq,lsass_in,lsass_out,s3,papi"
   }
  ]
 },
 "panels": [
  { "title": "Protocols", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Protocols Client Connections ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "Protocols",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by() (node_clientstats_connected_$${Protocols}_value{cluster=~\"$cluster\"})",
     "legendFormat": "Established $Protocols connections"
    },
    {
     "expr": "sum by() (node_clientstats_active_$${Protocols}_value{cluster=~\"$cluster\"})",
     "legendFormat": "active $Protocols connections"
    }
   ]
  },
  {
   "title": "$Protocols Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "repeat": "Protocols",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg_over_time(cluster_protostats_$${Protocols}_total_op_rate{cluster=~\"$cluster\"}[$__interval])",
     "legendFormat": "$Protocols ops"
    }
   ]
  },
  {
   "title": "$Protocols  Operation Mix",
   "type": "timeseries",
   "description": "Operation Count",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "repeat": "Protocols",
   "fieldConfig": { "defaults": { "unit": "Op" } },
   "targets": [
    {
     "expr": "avg_over_time(cluster_protostats_$${Protocols}_op_count{cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "{{op_name}} ({{class_name}})"
    },
    {
     "expr": "sum(cluster_protostats_$${Protocols}_op_count{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$Protocols Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "repeat": "Protocols",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "quantile(0.5, cluster_protostats_$${Protocols}_total_in_rate{cluster=~\"$cluster\"})",
     "legendFormat": "write"
    },
    {
     "expr": "quantile(0.5, cluster_protostats_$${Protocols}_total_out_rate{cluster=~\"$cluster\"})",
     "legendFormat": "read"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "$Protocols Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "repeat": "Protocols",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "quantile by(op_name,class_name) (0.5, cluster_protostats_$${Protocols}_in_rate{cluster=~\"$cluster\"})",
     "legendFormat": "{{op_name}} ({{class_name}}) write"
    },
    {
     "expr": "quantile by(op_name,class_name) (0.5, cluster_protostats_$${Protocols}_out_rate{cluster=~\"$cluster\"})",
     "legendFormat": "{{opt_name}} ({{class_name}}) read"
    }
   ]
  },
  {
   "title": "Average Latency for all $Protocols Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "repeat": "Protocols",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg_over_time(cluster_protostats_$${Protocols}_total_time_avg{cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "$Protocols avg"
    },
    {
     "expr": "avg_over_time(cluster_protostats_$${Protocols}_total_time_max{cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "$Protocols Max"
    },
    {
     "expr": "avg_over_time(cluster_protostats_$${Protocols}_total_time_min{cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "$Protocols Min"
    }
   ]
  },
  {
   "title": "Average Latency by $Protocols Operation ",
   "type": "timeseries",
   "description": "cluster.protostats.$Prototcols.time_avg broken out by class_name and op_name",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "repeat": "Protocols",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile by(op_name,class_name) (0.5, cluster_protostats_$${Protocols}_time_avg{cluster=~\"$cluster\"}) / 1000",
     "legendFormat": "{{op_name}}({{class_name}})"
    }
   ]
  },
  {
   "title": "Maximum Latency by $Protocols Operation",
   "type": "timeseries",
   "description": "cluster.protostats.$prototcol.time_max broken out by class_name and op_name",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "repeat": "Protocols",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(cluster_protostats_$${Protocols}_time_max{cluster=~\"$cluster\"}[1m]) / 1000",
     "legendFormat": "{{op_name}} ({{class_name}})"
    }
   ]
  }
 ]
}