{
 "title": "PowerScale Node Summary",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cluster_node_count_all_value,cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_net_int_errors_in_rate_value,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU SubSystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node $node Max CPU: sys",
   "type": "stat",
   "description": "Maximum value of sys during the interval",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(node_cpu_sys_max_value{cluster=~\"$cluster\", node=~\"$node\"} / 10)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node $node CPU Utilization",
   "type": "timeseries",
   "description": "Collection of the CPU based stats",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "quantile(0.5, node_cpu_idle_avg_value{cluster=~\"$cluster\", node=~\"$node\"} / 10)",
     "legendFormat": "idle"
    },
    {
     "expr": "quantile(0.5, node_cpu_intr_avg_value{cluster=~\"$cluster\", node=~\"$node\"}) / 10",
     "legendFormat": "inr"
    },
    {
     "expr": "quantile(0.5, node_cpu_nice_avg_value{cluster=~\"$cluster\", node=~\"$node\"}) / 10",
     "legendFormat": "nice"
    },
    {
     "expr": "quantile(0.5, node_cpu_sys_avg_value{cluster=~\"$cluster\", node=~\"$node\"}) / 10",
     "legendFormat": "sys"
    },
    {
     "expr": "quantile(0.5, node_cpu_user_avg_value{cluster=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Disk SubSystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Reads",
     "type": "timeseries",
     "description": "Average bytes read per second for all disks",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "quantile by(node) (0.5, node_disk_bytes_out_rate_avg_value{cluster=~\"$cluster\"})",
       "legendFormat": "Node {{node}}"
      }
     ]
    },
    {
     "title": "Disk Writes",
     "type": "timeseries",
     "description": "Average bytes read per second for all disks",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "quantile by(node) (0.5, node_disk_bytes_in_rate_avg_value{cluster=\"$cluster\"})",
       "legendFormat": "Node {{node}}"
      }
     ]
    },
    {
     "title": "Disk I/O Scheduler Latency",
     "type": "timeseries",
     "description": "Avg iosched latency for all disks",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile by(node) (0.5, node_disk_iosched_latency_avg_value{cluster=~\"$cluster\", node=~\"$node\"})",
       "legendFormat": "Node {{node}}"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "timeseries",
     "description": "Average access latency for all disks",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile by(node) (0.5, node_disk_access_latency_avg_value{cluster=~\"$cluster\", node=~\"$node\"})",
       "legendFormat": "Node {{node}}"
      }
     ]
    },
    {
     "title": "Disk I/O Scheduler Queue Length",
     "type": "timeseries",
     "description": "Avg iosched queue length for all disks",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(node_disk_iosched_queue_avg_value{cluster=~\"$cluster\", node=~\"$node\"}[1m])",
       "legendFormat": "Node {{node}}"
      }
     ]
    },
    {
     "title": "Disk Busy",
     "type": "timeseries",
     "description": "Average disk busy percent, per node.  The graph stacks the node contribbutions at 100% per node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time(node_disk_busy_avg_value{cluster=~\"$cluster\", node=~\"$node\"}[1m]) / 1000",
       "legendFormat": "Node {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "External Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "External Network Incoming Throughput",
     "type": "timeseries",
     "description": "This is a \"Stacked\" chart and the scale is the aggregate of all nodes displayed",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "quantile by(node) (0.5, node_net_ext_bytes_in_rate_value{cluster=\"$cluster\", node=~\"$node\"})",
       "legendFormat": "Node {{node}}"
      }
     ]
    },
    {
     "title": "External Network Outgoing Throughput",
     "type": "timeseries",
     "description": "This is a \"Stacked\" chart and the scale is the aggregate of all nodes displayed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "quantile by(node) (0.5, node_net_ext_bytes_out_rate_value{cluster=~\"$cluster\", node=~\"$node\"})",
       "legendFormat": "Node {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Internal Network Incoming Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg_over_time(node_net_int_bytes_in_rate_value{cluster=~\"$cluster\", node=~\"$node\"}[1m])",
       "legendFormat": "Node {{node}}"
      }
     ]
    },
    {
     "title": "Internal Network Outgoing Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg_over_time(node_net_int_bytes_out_rate_value{cluster=~\"$cluster\", node=~\"$node\"}[1m])",
       "legendFormat": "Node {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "External Network Errors",
     "type": "timeseries",
     "description": "Incoming errors per second for a node's external interfaces",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "avg by(node) (rate(node_net_ext_errors_in_rate_value{cluster=~\"$cluster\", node=~\"$node\"}[1m]))",
       "legendFormat": "incoming node {{node}}"
      },
      {
       "expr": "avg by(node) (rate(node_net_ext_errors_out_rate_value{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "outgoing {{node}}"
      }
     ]
    },
    {
     "title": "Internal Network Errors",
     "type": "timeseries",
     "description": "Errors per second for a node's internal interfaces",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "avg by(node) (rate(node_net_int_errors_in_rate_value{cluster=~\"$cluster\"}[1m]))",
       "legendFormat": "incoming node {{node}}"
      },
      {
       "expr": "avg by(node) (rate(node_net_int_errors_out_rate_value{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "outgoing {{node}}"
      }
     ]
    }
   ]
  }
 ]
}