{
 "title": "Powerscale Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cluster_node_count_all_value,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Look", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_node_count_all_value{cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Diskless Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_node_count_diskless_value{cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_health_value{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SmartFailed Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster_node_count_smartfailed_value{cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster_node_count_down_value{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read-only Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster_node_count_readonly_value{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (cluster_cpu_idle_avg_value{cluster=\"$cluster\"}/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Capacity Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - quantile(0.5,ifs_percent_avail_value{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inline Dedupe Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, cluster_dedupe_inline_ratio_value{cluster=~\"$cluster\"})",
     "legendFormat": "inline"
    }
   ]
  },
  {
   "title": "Cluster Compression",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, cluster_compression_ratio_value{cluster=~\"$cluster\"})",
     "legendFormat": "inline"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Network Read Throughput",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "cluster_net_ext_bytes_out_rate_value{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg. Network Write Throughput",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "cluster_net_ext_bytes_in_rate_value{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max hdfs Read Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_hdfs_total_out_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max nfs Read Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_nfs_total_out_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max nfs4 Read Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_nfs4_total_out_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max smb2 Read Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_smb2_total_out_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max siq Read Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_siq_total_out_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max lsass_in Read Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_lsass_in_total_out_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max lsass_out Read Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_lsass_out_total_out_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max hdfs Write Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_hdfs_total_in_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max nfs Write Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_nfs_total_in_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max nfs4 Write Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_nfs4_total_in_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max smb2 Write Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_smb2_total_in_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max siq Write Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_siq_total_in_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max lsass_in Write Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_lsass_in_total_in_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max lsass_out Write Throughput",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(cluster_protostats_lsass_out_total_in_rate{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Cluster CPU Breakdown - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "quantile(0.5,cluster_cpu_intr_avg_value{cluster=\"$cluster\"})/1000",
     "legendFormat": "intr"
    },
    {
     "expr": "quantile(0.5,cluster_cpu_sys_avg_value{cluster=\"$cluster\"})/10",
     "legendFormat": "sys"
    },
    {
     "expr": "quantile(0.5,cluster_cpu_user_avg_value{cluster=\"$cluster\"})/10",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Heat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile(0.5,{__name__=~\"node_ifs_heat_.+_total_value\",cluster=\"$cluster\"}) by (__name__)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Filesystem Heat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Max lsass_out Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(quantile(0.5,cluster_protostats_lsass_out_time_max{cluster=\"$cluster\"}) by (class_name,op_name))/1000",
     "legendFormat": "{{op_name}}({{class_name}})"
    }
   ]
  },
  {
   "title": "Total File Operations and Capacity Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total /ifs Operations",
     "type": "timeseries",
     "description": "Writes are plotted on negative y-axis to contrast with reads",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "quantile(0.5,ifs_bytes_in_rate_value{cluster=\"$cluster\"})",
       "legendFormat": "Writes"
      },
      {
       "expr": "quantile(0.5,ifs_bytes_out_rate_value{cluster=\"$cluster\"})",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Capacity Cluster Wide",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "quantile(0.5,ifs_bytes_used_value{cluster=\"$cluster\"})",
       "legendFormat": "Bytes Used"
      },
      {
       "expr": "quantile(0.5,ifs_bytes_total_value{cluster=\"$cluster\"})",
       "legendFormat": "Bytes Available"
      },
      { "expression": "$A/$B", "type": "math" }
     ]
    },
    {
     "title": "Cluster Data Reduction ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "quantile(0.5, cluster_compression_ratio_value{cluster=\"$cluster\"})",
       "legendFormat": "Compression Ratio"
      },
      {
       "expr": "quantile(0.5, cluster_dedupe_inline_ratio_value{cluster=\"$cluster\"})",
       "legendFormat": "Dedupe Ratio"
      }
     ]
    }
   ]
  },
  {
   "title": "L1 Cache Efficency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "L1 Prefetch Cache - $cluster",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max(node_ifs_cache_l1_data_prefetch_hit{cluster=\"$cluster\"})/max(node_ifs_cache_l1_data_prefetch_start{cluster=\"$cluster\"})",
       "legendFormat": "L1 Data"
      },
      {
       "expr": "max(node_ifs_cache_l1_meta_prefetch_hit{cluster=\"$cluster\"})/max(node_ifs_cache_l1_meta_prefetch_start{cluster=\"$cluster\"})",
       "legendFormat": "L1 Metadata"
      }
     ]
    },
    {
     "title": "L1 Cache - $cluster",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(node_ifs_cache_l1_data_read_hit{cluster=\"$cluster\"})/max(node_ifs_cache_l1_data_read_start{cluster=\"$cluster\"})",
       "legendFormat": "L1 Data"
      },
      {
       "expr": "max(node_ifs_cache_l1_meta_read_hit{cluster=\"$cluster\"})/max(node_ifs_cache_l1_meta_read_start{cluster=\"$cluster\"})",
       "legendFormat": "L1 Metadata"
      }
     ]
    }
   ]
  },
  {
   "title": "L2 Cache Efficency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "L2 Prefetch Cache - $cluster",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max(node_ifs_cache_l2_data_prefetch_hit{cluster=\"$cluster\"})/max(node_ifs_cache_l2_data_prefetch_start{cluster=\"$cluster\"})",
       "legendFormat": "L2 Data"
      },
      {
       "expr": "max(node_ifs_cache_l2_meta_prefetch_hit{cluster=\"$cluster\"})/max(node_ifs_cache_l2_meta_prefetch_start{cluster=\"$cluster\"})",
       "legendFormat": "L2 Metadata"
      }
     ]
    },
    {
     "title": "L2 Cache - $cluster",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(node_ifs_cache_l2_data_read_hit{cluster=\"$cluster\"})/max(node_ifs_cache_l2_data_read_start{cluster=\"$cluster\"})",
       "legendFormat": "L2 Data"
      },
      {
       "expr": "max(node_ifs_cache_l2_meta_read_hit{cluster=\"$cluster\"})/max(node_ifs_cache_l2_meta_read_start{cluster=\"$cluster\"})",
       "legendFormat": "L2 Metadata"
      }
     ]
    }
   ]
  },
  {
   "title": "L3 Cache Efficency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "L3 Cache - $cluster",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(node_ifs_cache_l3_data_read_hit{cluster=\"$cluster\"})/max(node_ifs_cache_l3_data_read_start{cluster=\"$cluster\"})",
       "legendFormat": "L3 Data"
      },
      {
       "expr": "max(node_ifs_cache_l3_meta_read_hit{cluster=\"$cluster\"})/max(node_ifs_cache_l3_meta_read_start{cluster=\"$cluster\"})",
       "legendFormat": "L3 Metadata"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IO for $cluster",
     "type": "timeseries",
     "description": "THis is a stacked graph so the total R+W is plotted for the overall B/W.  At the same time showing the contributions from each.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "quantile(0.5,cluster_disk_bytes_in_rate_value{cluster=\"$cluster\"})",
       "legendFormat": "Writes"
      },
      {
       "expr": "quantile(0.5,cluster_disk_bytes_out_rate_value{cluster=\"$cluster\"})",
       "legendFormat": "Reads"
      }
     ]
    },
    {
     "title": "External Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "quantile(0.5,cluster_net_ext_bytes_in_rate_value{cluster=\"$cluster\"})",
       "legendFormat": "Writes"
      },
      {
       "expr": "quantile(0.5,cluster_net_ext_bytes_out_rate_value{cluster=\"$cluster\"})",
       "legendFormat": "Reads"
      }
     ]
    }
   ]
  }
 ]
}