apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus
  labels:
    pod-security.kubernetes.io/enforce: privileged
    kyverno.io/exclude-rule: "true"
spec: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: kube-prometheus
spec:
  interval: 1m
  timeout: 20m
  chart:
    spec:
      chart: kube-prometheus
      version: 11.1.20
      sourceRef:
        kind: HelmRepository
        name: local-harbor-helm-repo
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  releaseName: kube-prometheus
  valuesFrom:
  - kind: ConfigMap
    name: kube-prometheus-values
  postRenderers:
  - kustomize:
      images:
      - name: docker.io/bitnami/alertmanager:0.28.1-debian-12-r9
        newName: ${registry_host}/platform/kube-prometheus-images
        digest: sha256:sha256:84eff0009d53e9b29d027f006c76a8a2e55fd400913cb8ad5bef597902cefadc
      - name: docker.io/bitnami/blackbox-exporter:0.26.0-debian-12-r10
        newName: ${registry_host}/platform/kube-prometheus-images
        digest: sha256:sha256:bb10d12fe1a124e196602870419f1a22233606c47f28d7e5bf850a630f7308a9
      - name: docker.io/bitnami/kube-state-metrics:2.15.0-debian-12-r11
        newName: ${registry_host}/platform/kube-prometheus-images
        digest: sha256:sha256:80529c1b9838b3cdc465c5de4b9400737847e42cc7d20cd78111cc2a75c3b76f
      - name: docker.io/bitnami/node-exporter:1.9.1-debian-12-r4
        newName: ${registry_host}/platform/kube-prometheus-images
        digest: sha256:sha256:2f405cc9df8e758dcafe3956d734c3adac2be79564f5d731b6773bf0d1176954
      - name: docker.io/bitnami/prometheus-operator:0.83.0-debian-12-r2
        newName: ${registry_host}/platform/kube-prometheus-images
        digest: sha256:sha256:3ee1f4708bbd756b9b4a2152550608079dc602b6df4ec997d4454d9fa79032d1
      - name: docker.io/bitnami/prometheus:3.4.1-debian-12-r1
        newName: ${registry_host}/platform/kube-prometheus-images
        digest: sha256:sha256:93a0d622d8e183185394b2491cadf7cc874b64292da9004316af25a3f91080c5
      - name: ubuntu:23.04
        newName: ${registry_host}/platform/kube-prometheus-images
        digest: sha256:sha256:7162767f3c86c5be37020f5305e783f03b8160c5081af286fe0214f9c0e1d463
