apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 1m
  timeout: 20m
  chart:
    spec:
      chart: trust-manager
      version: v0.12.0
      sourceRef:
        kind: HelmRepository
        name: local-harbor-helm-repo
        namespace: flux-system
      interval: 5m
  releaseName: trust-manager
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  valuesFrom:
  - kind: ConfigMap
    name: trust-manager-values
  postRenderers:
  - kustomize:
      images:
      - name: quay.io/jetstack/cert-manager-package-debian:20210119.0
        newName: ${registry_host}/platform/trust-manager-images
        digest: sha256:sha256:e6569a92bc9033896bd1f24235aff14afeb3f178d58af84f8d7e5364d066c317
      - name: quay.io/jetstack/trust-manager:v0.12.0
        newName: ${registry_host}/platform/trust-manager-images
        digest: sha256:sha256:668965da699915cd69727dc01c8b93bb3b2e41f3b693294985d6904bc00f0797
