apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- selfsigned-cluster-issuer.yaml
- trust-manager-bundle.yaml
- kyverno-policies-extras.yaml
- k8s-cert-probe.yaml
- fluxcd-podmonitor.yaml
- k8s-control-plane-smon.yaml
