{
 "title": "High-level-VM-Resource-Utilization(Linux)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "vm_group",
    "query": {
     "query": "label_values(system_uptime_seconds{os_type=\"linux\"},vm_group)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(system_uptime_seconds{vm_group=\"$vm_group\", os_type=\"linux\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Utilization",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{vm_group=~\".*.\", host_name=~\".*.\",os_type=\"linux\",state=\"used\"}/ ignoring(state) system_memory_limit_bytes{vm_group=~\".*.\", host_name=~\".*.\", os_type=\"linux\"} > 0.80",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (host_name)(system_cpu_utilization_ratio{vm_group=~\".*.\", host_name=~\".*.\",os_type=\"linux\", state!=\"idle\"}) / sum by (host_name)(system_cpu_physical_count{vm_group=~\".*.\",host_name=~\".*.\",os_type=\"linux\"})) > 0.8\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FileSystem Utilization",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(mountpoint, host_name) (system_filesystem_utilization_ratio{vm_group=~\".*.\", host_name!=\"localhost\",os_type=\"linux\", mountpoint!~\"/snap/.*|/var/lib/snapd/.*\"}) > 0.9",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}