{
 "title": "VM Details",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "vm_group",
    "label": "VM Group",
    "query": {
     "query": "label_values(system_uptime_seconds{os_type=\"linux\"},vm_group)"
    }
   },
   {
    "name": "node_name",
    "label": "VM/Host Name",
    "query": {
     "query": "label_values(system_uptime_seconds{vm_group=\"$vm_group\", os_type=\"linux\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VM Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime_seconds{host_name=\"$node_name\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "OS Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "system_uptime_seconds{vm_group=\"$vm_group\", host_name=\"$node_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "system_uptime_seconds{vm_group=\"$vm_group\", host_name=\"$node_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kernel Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "system_uptime_seconds{vm_group=\"$vm_group\", host_name=\"$node_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_physical_count{host_name=\"$node_name\",vm_group=\"$vm_group\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_frequency_hertz{host_name=\"$node_name\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_limit_bytes{host_name=\"$node_name\",vm_group=\"$vm_group\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Processes Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_processes_count{host_name=\"$node_name\",vm_group=\"$vm_group\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage % per CPU State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(system_cpu_utilization_ratio{host_name=\"$node_name\", state!=\"idle\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU Usage % per CPU Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cpu) (system_cpu_utilization_ratio{host_name=\"$node_name\", state!=\"idle\"})",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(state) (system_memory_usage_bytes{host_name=\"$node_name\", state!=\"free\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total{host_name=\"$node_name\", device=~\"ens.+|eth.+\",direction=\"receive\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}} - {{direction}}"
    },
    {
     "expr": "1-rate(system_network_io_bytes_total{host_name=\"$node_name\", device=~\"ens.+|eth.+\",direction=\"transmit\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_filesystem_utilization_ratio{host_name=\"$node_name\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_disk_io_bytes_total{host_name=\"$node_name\", device=~\"...\"}[$__rate_interval])",
     "legendFormat": "{{device}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Network Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "1-rate(system_network_packets_total{host_name=\"$node_name\", device=~\"ens.+|eth.+\", direction=\"receive\"}[$__rate_interval])",
     "legendFormat": "{{device}} - {{direction}}"
    },
    {
     "expr": "rate(system_network_packets_total{host_name=\"$node_name\", device=~\"ens.+|eth.+\", direction=\"transmit\"}[$__rate_interval])",
     "legendFormat": "{{device}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Disk IO Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(system_disk_operation_time_seconds_total{host_name=\"$node_name\",device=~\"...\"}[$__rate_interval])",
     "legendFormat": "{{device}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(rate(system_disk_operation_time_seconds_total{host_name=\"$node_name\",device=~\"...\"}[$__rate_interval]) / rate(system_disk_operations_total{host_name=\"$node_name\",device=~\"...\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{device}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Network Packet Drop & Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(system_network_dropped_total{host_name=\"$node_name\", device=~\"ens.+|eth.+\"}[$__rate_interval])",
     "legendFormat": "Dropped - {{device}} - {{direction}}"
    },
    {
     "expr": "rate(system_network_errors_total{k8s_node_name=\"$node_name\", device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "Error - {{direction}}"
    }
   ]
  },
  {
   "title": "Network Connection State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "system_network_connections{host_name=\"$node_name\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Disk IO Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "system_disk_pending_operations{host_name=\"$node_name\", device=~\"...\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}