apiVersion: v1
kind: Namespace
metadata:
  name: contour
  labels:
    pod-security.kubernetes.io/enforce: privileged
    kyverno.io/exclude-rule: "true"
spec: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  interval: 1m
  timeout: 20m
  chart:
    spec:
      chart: contour
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: local-harbor-helm-repo
        namespace: flux-system
      interval: 5m
  releaseName: contour
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  - name: splunk-otel-collector
    namespace: splunk
  valuesFrom:
  - kind: ConfigMap
    name: contour-values
  postRenderers:
  - kustomize:
      images:
      - name: ghcr.io/projectcontour/contour:v1.33.3
        newName: ${registry_host}/platform/contour-images
        digest: sha256:sha256:ab3cc807429d452e1086ecda2e1a083f2dbb0027fca2a15d29a390b81dc7eb81
      - name: docker.io/envoyproxy/envoy:v1.35.9
        newName: ${registry_host}/platform/contour-images
        digest: sha256:sha256:37c31497c8ed4891e97b5489ba669c1c11c24c9e90ee29a03c0598f9cec7782e
