apiVersion: v1
kind: Namespace
metadata:
  name: contour
  labels:
    pod-security.kubernetes.io/enforce: privileged
    kyverno.io/exclude-rule: "true"
spec: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  interval: 1m
  timeout: 20m
  chart:
    spec:
      chart: contour
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: local-harbor-helm-repo
        namespace: flux-system
      interval: 5m
  releaseName: contour
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  - name: splunk-otel-collector
    namespace: splunk
  valuesFrom:
  - kind: ConfigMap
    name: contour-values
  postRenderers:
  - kustomize:
      images:
      - name: ghcr.io/projectcontour/contour:v1.33.3
        newName: ${registry_host}/platform/contour-images
        digest: sha256:beb9c82dc35187a794aafb7e0ccdd38b13114ae35d1dcba3c4f7601db1bb784c
      - name: docker.io/envoyproxy/envoy:v1.35.9
        newName: ${registry_host}/platform/contour-images
        digest: sha256:cdd2b55ac98dc9ddfc026cb3988453424861773886aea7d24242702c90c44b1b
